FROM ubuntu:18.04

RUN apt-get update && apt-get install -y software-properties-common git curl unrar-free p7zip-full p7zip-rar unzip wget rsync
RUN add-apt-repository ppa:ondrej/php && apt-get update