name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.4

      - name: List all changed files
        run: |
          function build_and_publish(){
            USER=$1
            REPO=$2
            TAG=$3
            REPO_TWO=$4
            TAG_TWO=$5
            IMAGE="$1/$REPO:$TAG"
            IMAGE_TWO="$1/$REPO_TWO:$TAG_TWO"
            docker build -t $IMAGE -t $IMAGE_TWO - < "./dockerfiles/$TAG.Dockerfile"
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker push $IMAGE
            docker push $IMAGE_TWO
          }
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"

            CHECKFILE="dockerfiles/deb11-p74-n10-c233.Dockerfile"
            if [ $file == "$CHECKFILE" ] || [ $file == ".build_and_publish_all" ]; then
              build_and_publish "binbiriz" "drupal" "deb11-p74-n10-c233" "debian-11-php7.4" "c233-node10"
            fi

            CHECKFILE="dockerfiles/deb11-p74-n10-c2212.Dockerfile"
            if [ $file == "$CHECKFILE" ] || [ $file == ".build_and_publish_all" ]; then
              build_and_publish "binbiriz" "drupal" "deb11-p74-n10-c2212" "debian-11-php7.4" "c2212-node10"
            fi
          done
