name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
    - dockerfiles
  pull_request:
    branches: [ "main" ]
    paths:
    - dockerfiles

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: binbiriz/drupal
          tags: deb11-p74-n10-c2212
          registry: docker.io
          dockerfile: dockerfiles/deb11-p74-n10-c2212.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
