name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.4

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            if [ $file == "dockerfiles/u2004-p81-nna-c233.Dockerfile" ] || [ $file == ".build_and_publish_all" ]; then
              DFILE="dockerfiles/u2004-p81-nna-c233.Dockerfile"
              IMAGE="binbiriz/drupal:u2004-p81-nna-c233"
              docker build -t $IMAGE - < $DFILE
              docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
              docker push $IMAGE
            fi
            if [ $file == "dockerfiles/u1804-p80-nna-c2212.Dockerfile" ] || [ $file == ".build_and_publish_all" ]; then
              DFILE="dockerfiles/u1804-p80-nna-c2212.Dockerfile"
              IMAGE="binbiriz/drupal:u1804-p80-nna-c2212"
              docker build -t $IMAGE - < $DFILE
              docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
              docker push $IMAGE
            fi
          done
